words = [
    "ALTERADO", "CONSTRUCCION", "DEPORTISTA", "ESDRUJULA", "INFORMATICO",
    "NOVICIA", "NOCTURNO", "PESADILLA", "CADERA", "CANDADO", "TEMPANO",
    "HERMANO", "VERDAD", "INVITACION", "PREPARACION"
]